version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  publish:
    description: Setup and run application tests
    working_directory: C:\Users\circleci\project\WebApp
    executor:
      name: windows/default
    steps:
      - checkout
        - run:
            name: List Projects
            working_directory: C:\Users\circleci\project
            command: dir

      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore                  
  
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  publish_and_build:
    jobs:
      - publish      