version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  publish:
    description: Setup and run application tests
    working_directory: C:\Users\circleci\project\WebApp
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Clone EnageWebService
          working_directory: C:\Users\circleci\project
          command: git clone -b << pipeline.git.branch >> https://github.com/asanthosh69/EnageWebService.git
               
      - run:
          name: Build Project
          working_directory: C:\Users\circleci\project\EnageWebService
          command: MSBuild.exe -m EnageWebService.sln /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true
      - run:
          name: Copy build content of  Project EngageWebService
          working_directory: C:\Users\circleci\project\EnageWebService\bin
          command:  Copy-Item -Path .\Release\ -Destination C:\Users\circleci\project\EngageWebService-Build -Force -Recurse     

      - run:
          name: List Projects
          working_directory: C:\Users\circleci\project
          command: dir

      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore                  
  #C:\Users\circleci\project\WebApp\WebAppCore\bin\Release
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet build WebAppCore.sln /p:PublishProfile=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:platform="Any CPU" /p:configuration="Release" 
      - run:
          name: Copy build content of  Project WebApp
          working_directory: C:\Users\circleci\project\WebApp\WebAppCore\bin\Release
          command: |
            Copy-Item -Path .\netcoreapp2.1\ -Destination C:\Users\circleci\project\WebApp-Build -Force -Recurse
      - run:
          name: list
          working_directory:  C:\Users\circleci\project
          command:  dir

      - persist_to_workspace:
          root: C:\Users\circleci\project
          paths:
            - EngageWebService-Build            
            - WebApp-Build
  deploy:
    docker:
    - image: circleci/python:3.6.4
    description: Deploy
    steps:     
      - attach_workspace:
          at: ~/repo/project
      - run:
          name: List Data
          working_directory: ~/repo/project/WebApp-Build
          command: |
            ls
      - run:
          name: List Data
          working_directory: ~/repo/project/WebApp-Build
          command: |
            unzip WebAppCore.zip -d WebApp
            cp -R WebApp/Content/C_C/Users/circleci/project/WebApp/WebAppCore/obj/Release/netcoreapp2.1/PubTmp/Out ~/repo/project/WebApp
            rm -rf ~/repo/project/WebApp-Build
      - run:
          name: List Data
          working_directory: ~/repo/project
          command: |
            ls            
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/project
          command: |
           # sudo pip install --upgrade pip
           sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
             mkdir ~/repo/project/.aws
             touch ~/repo/project/.aws/config
             chmod 600  ~/repo/project/.aws/config
             echo "[profile saamaws]" > ~/repo/project/.aws/config
             echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/project/.aws/config
             echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/project/.aws/config
      - run:
          name: EB Upload and Deploy
          working_directory: ~/repo/project
          command: |
            eb init --region us-east-1 --platform iis-10.0 Webappcore-env
            eb create --keyname saamumpk.pem WebAppCore-dev
            #eb deploy WebAppCore-dev        

workflows:
  publish_and_build:
    jobs:
      - publish
      - Hold:
          type: approval
          requires:
            - publish
      - deploy:          
          requires:
            - Hold
          filters:
            branches:
              only:
                - << pipeline.git.branch >>                
                

