version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  publish:
    description: Setup and run application tests
    working_directory: C:\Users\circleci\project\WebApp
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Clone EnageWebService
          working_directory: C:\Users\circleci\project
          command: git clone -b << pipeline.git.branch >> https://github.com/asanthosh69/EnageWebService.git
               
      - run:
          name: Build Project
          working_directory: C:\Users\circleci\project\EnageWebService
          command: MSBuild.exe -m EnageWebService.sln /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true
      - run:
          name: Copy build content of  Project EngageWebService
          working_directory: C:\Users\circleci\project\EnageWebService\bin
          command:  Copy-Item -Path .\Release\ -Destination C:\Users\circleci\project\EngageWebService-Build -Force -Recurse     

      - run:
          name: List Projects
          working_directory: C:\Users\circleci\project
          command: dir

      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore                  
  #C:\Users\circleci\project\WebApp\WebAppCore\bin\Release
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
      - run:
          name: Copy build content of  Project WebApp
          working_directory: C:\Users\circleci\project\WebApp\WebAppCore\bin\Release
          command: |
            Copy-Item -Path .\Package\ -Destination C:\Users\circleci\project\WebApp-Build -Force -Recurse
      - run:
          name: list
          working_directory:  C:\Users\circleci\project
          command:  dir

      - persist_to_workspace:
          root: C:\Users\circleci\project
          paths:
            - EngageWebService-Build            
            - WebApp-Build            

workflows:
  publish_and_build:
    jobs:
      - publish    
